/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9keyy4C6lG7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import Link from "next/link"

export function CreateSearchPost() {
  return (
    <Card className="w-full max-w-md p-6">
      <div className="flex flex-col items-start gap-4">
        <div>
          <h3 className="text-2xl font-semibold">Manage Posts</h3>
          <p className="text-muted-foreground">Create new posts or search existing ones.</p>
        </div>
        <div className="flex w-full gap-4">
          <Link
            href="#"
            className="flex-1 inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-1 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
          >
            Create Post
          </Link>
          <Link
            href="#"
            className="flex-1 inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-muted-foreground shadow-sm transition-colors hover:bg-muted hover:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring focus:ring-offset-2"
            prefetch={false}
          >
            Search Post
          </Link>
        </div>
      </div>
    </Card>
  )
}
