/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KUVyersp4yT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export function JobCard() {
  return (
    <Card className="w-full  p-6 grid gap-6">
      <div className="flex items-center gap-4">
        <div className="bg-muted rounded-md flex items-center justify-center aspect-square w-12">
          <img src="/placeholder.svg" width={40} height={40} alt="Company Logo" className="object-contain" />
        </div>
        <div className="flex-1">
          <h3 className="text-lg font-semibold">Senior Frontend Engineer</h3>
          <p className="text-muted-foreground">Acme Inc.</p>
        </div>
      </div>
      <div className="text-muted-foreground">
        We are looking for a Senior Frontend Engineer to join our team. You will be responsible for building and
        maintaining our web application, which is built using React, TypeScript, Next.js, and Tailwind CSS. You should
              </div>
      <div className="flex flex-wrap gap-2 justify-start">
        <Badge variant="outline">React</Badge>
        <Badge variant="outline">TypeScript</Badge>
        <Badge variant="outline">Next.js</Badge>
        <Badge variant="outline">Tailwind CSS</Badge>
      </div>
      <div className="flex justify-between items-end">
        <div className="text-muted-foreground">Salary: 8lpa</div>
        <Button>Apply</Button>
      </div>
    </Card>
  )
}
