/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/AqqckCqRP55
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import Image from "next/image"

export function PortfolioCard() {
  return (
    <Card className="w-full rounded-lg overflow-hidden">
      <div className="flex items-center justify-between p-4 bg-background">
        <h3 className="text-lg font-semibold">Latest Portfolio</h3>
        <Button variant="ghost" size="icon">
          <FilePenIcon className="h-5 w-5" />
          <span className="sr-only">Edit</span>
        </Button>
      </div>
      <Link href="#" className="group block" prefetch={false}>
        <div className="p-4">
          <Image
            src="/placeholder.svg"
            alt="Card Image"
            width={400}
            height={240}
            className="w-full h-60 object-cover group-hover:scale-105 transition-transform duration-300 ease-in-out"
          />
        </div>
      </Link>
    </Card>
  )
}

function FilePenIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  )
}
