/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VaXSiA2PZwp
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";

export function UserList() {
  return (
    <Card className="w-full max-w-4xl  z-0">
      <CardHeader className="border-b  py-4">
        <CardTitle>Placed Users</CardTitle>
      </CardHeader>
      <CardContent className="max-h-[500px] overflow-y-auto">
        <div className="grid gap-4  py-4">
          
          <div className="flex items-center gap-4">
            <Avatar className="border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
            <div className="flex-1">
              <h4 className="font-bold">Shu Ding</h4>
              <p className="text-sm text-muted-foreground">Product Designer</p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <Avatar className="border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>ML</AvatarFallback>
            </Avatar>
            <div className="flex-1">
              <h4 className="font-bold">Max Leiter</h4>
              <p className="text-sm text-muted-foreground">
                Frontend Developer
              </p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <Avatar className="border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>SD</AvatarFallback>
            </Avatar>
            <div className="flex-1">
              <h4 className="font-bold">Shu Ding</h4>
              <p className="text-sm text-muted-foreground">Backend Developer</p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <Avatar className="border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
            <div className="flex-1">
              <h4 className="font-bold">Shu Ding</h4>
              <p className="text-sm text-muted-foreground">Product Designer</p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <Avatar className="border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>ML</AvatarFallback>
            </Avatar>
            <div className="flex-1">
              <h4 className="font-bold">Max Leiter</h4>
              <p className="text-sm text-muted-foreground">
                Frontend Developer
              </p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <Avatar className="border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>SD</AvatarFallback>
            </Avatar>
            <div className="flex-1">
              <h4 className="font-bold">Shu Ding</h4>
              <p className="text-sm text-muted-foreground">Backend Developer</p>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
