import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/component/Navbar";
import { ThemeProvider } from "@/components/component/theme-provider";
import {Toaster } from "sonner"
import StoreProvider from "./StoreProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Refro",
  description: "Generated by create next app",
};

const  RootLayout=({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)=> {
  return (
    <html lang="en" >
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
       <StoreProvider>
       <Navbar/>
       {children}
       </StoreProvider>
        <Toaster  position="top-center" richColors	 />
        </ThemeProvider></body>
    </html>
  );
}
export default RootLayout;